categories: Categories
search: Search
tags: Tags
tagcloud: Album
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
writed_by: Edited by
powered_by: Powered by
supported_by_uv: "Reader:"
supported_by_pv: "times:"
rss_feed: RSS Feed
category: Category
tag: Tag
qrcode: QR Code
tip: Tip